spring:
  application:
    name: phone_selling_app

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/phone_selling_app
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  service:
    cors:
      baseUrl: http://localhost:3000
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
  security:
    jwt:
      secret: JHD2p1EolyuH3K6Gjz05onMO5hRT8CYHJHD2p1EolyuH3K6Gjz05onMO5hRT8CYH
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - urlPattern: /api/v1/users/login-customer
          method: POST
        - urlPattern: /api/v1/users/login-admin
          method: POST
        - urlPattern: /api/v1/users/login-staff
          method: POST
        - urlPattern: /api/v1/users/register-customer
          method: POST
      protectedUrls:
        - urlPattern: /api/v1/users/register
          roles:
            - ADMIN
