spring:
  application:
    name: phone_selling_app

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/phone_selling_app
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb+srv://kienpham1392004:1392004kien@cluster0.byk8u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: phone_selling_app

app:
  service:
    cors:
      baseUrl: http://localhost:3000
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
  security:
    jwt:
      secret: JHD2p1EolyuH3K6Gjz05onMO5hRT8CYHJHD2p1EolyuH3K6Gjz05onMO5hRT8CYH
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - urlPattern: /api/v1/personal/login-customer
          method: POST
        - urlPattern: /api/v1/personal/login-admin
          method: POST
        - urlPattern: /api/v1/personal/login-staff
          method: POST
        - urlPattern: /api/v1/personal/register-customer
          method: POST
      protectedUrls:
        - urlPattern: /api/v1/personal/rename
          roles:
            - CUSTOMER
            - ADMIN
            - STAFF
        - urlPattern: /api/v1/personal/change-password
          roles:
            - CUSTOMER
            - ADMIN
            - STAFF
        - urlPattern: /api/v1/users/**
          roles:
            - ADMIN
        - urlPattern: /api/v1/shipping-infos/**
          roles:
            - CUSTOMER
        - urlPattern: /api/v1/images/**
          roles:
            - STAFF
        - urlPattern: /api/v1/brands/**
          roles:
            - STAFF
