spring:
  application:
    name: phone_selling_app

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/phone_selling_app
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  service:
    cors:
      baseUrl: http://localhost:3000
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
  security:
    jwt:
      secret: JHD2p1EolyuH3K6Gjz05onMO5hRT8CYHJHD2p1EolyuH3K6Gjz05onMO5hRT8CYH
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - urlPattern: /api/auth/login
          method: POST
        - urlPattern: /api/auth/sign-up
          method: POST
        - urlPattern: /api/colors
          method: GET
        - urlPattern: /api/categories
          method: GET
        - urlPattern: /api/products/search
          method: GET
      protectedUrls:
        - urlPattern: /api/orders/my-order
          roles:
            - USER
        - urlPattern: /api/shipping-infos/my-shipping-infos
          roles:
            - USER
        - urlPattern: /api/carts/my-carts
          roles:
            - USER
        - urlPattern: /api/carts/**
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/colors/**
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/categories/**
          roles:
            - ADMIN
            - MODERATOR
        - urlPattern: /api/products/**
          roles:
            - ADMIN
            - MODERATOR
